# Sideproject: Using `pandas` and `seaborn` to analyze Stackoverflow Developer Survey results !

## * Work in progress. Not ready for viewing yet...

This file will include Loading, Cleaning, Wrangling, and the initial steps of Explorative analysis. 

Later I will separate the Loading + Transformation from Analysis and then from Insights / Vis.

## Load the Data

`df` = survey results

`dfs` = question schema

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../raw-data/2022-stack-dev-surv/survey_results_public.csv')
dfs =  pd.read_csv('../raw-data/2022-stack-dev-surv/survey_results_schema.csv')
df.head()

C:\Users\mariu\AppData\Local\Temp\ipykernel_40864\938543504.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [2]:

#Show us all of the columns
pd.set_option('display.max_columns', None)
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

### Renames for clarity

In [3]:
df.rename(columns = {'ResponseId':'ResponseID'}, inplace = True)

### Cleansing and post processing in order to read the contents in the order in which they were asked

In [4]:
# dfs will hold the qid stripped away to its number component
dfs['qid'] = dfs['qid'].apply(lambda x: x.replace('QID', ''))

#qid column will now hold an integer value, not a string
dfs['qid'] = pd.to_numeric(dfs['qid'])

## Project planning

In [5]:


"""

To split in a few tables:
- Participants - who they are (Basic Info + Demographics)
- Education and learning (Education+Work+Career, Work experience)
- Work (employment, career, teams/work experience)

I will use the Tech and culture to focus on Data Science ?

Converted Q yearly means currency transaction done. USD

Team soft/hard interesting but leave alone. have enough for now. there its really personality asses and take grain salt

How many even answer for cert

Teams questions includes work experience (repeat for that which covers same question)

There is a field called 'other' for many questions. cant get to finding those answers.
for many, incl:
missing, so what does that mean. disregard column, ignore, etc.

The numbers in schema include the multiple choice answers

Questions to look into
* how many out of soft skills did X and Y in their background
* most common advice for learning fast
* can you get good without doing coding as a hobby, so only 9-5
* self taught and non hobby, how important team is
* is a larger org more supportive, do people have a faster path there ?


Existing analyses:
https://stackoverflow.blog/2021/12/07/new-data-what-developers-look-for-in-future-job-opportunities/
https://www.docker.com/blog/key-insights-from-stack-overflows-2022-developer-survey/
https://www.educative.io/blog/stackoverflow-dev-survey-key-takeaways-learners
https://survey.stackoverflow.co/2022/

"""

"\n\nTo split in a few tables:\n- Participants - who they are (Basic Info + Demographics)\n- Education and learning (Education+Work+Career, Work experience)\n- Work (employment, career, teams/work experience)\n\nI will use the Tech and culture to focus on Data Science ?\n\nConverted Q yearly means currency transaction done. USD\n\nTeam soft/hard interesting but leave alone. have enough for now. there its really personality asses and take grain salt\n\nHow many even answer for cert\n\nTeams questions includes work experience (repeat for that which covers same question)\n\nThere is a field called 'other' for many questions. cant get to finding those answers.\nfor many, incl:\nmissing, so what does that mean. disregard column, ignore, etc.\n\nThe numbers in schema include the multiple choice answers\n\nQuestions to look into\n* how many out of soft skills did X and Y in their background\n* most common advice for learning fast\n* can you get good without doing coding as a hobby, so only 9-5\n* self taught and non hobby, how important team is\n* is a larger org more supportive, do people have a faster path there ?\n\n\nExisting analyses:\nhttps://stackoverflow.blog/2021/12/07/new-data-what-developers-look-for-in-future-job-opportunities/\nhttps://www.docker.com/blog/key-insights-from-stack-overflows-2022-developer-survey/\nhttps://www.educative.io/blog/stackoverflow-dev-survey-key-takeaways-learners\nhttps://survey.stackoverflow.co/2022/\n\n"

## Misc Notes

In [6]:
# Explore the data, draw conclusions on where to focus- from schema and research objectives

In [7]:
# Examine the schema to understand the survey better

In [8]:
# Risk of focusing only on a small subset of answers: Machine learning/ data.
# Perhaps widen to all dev and see what diff ? is 5% * 30K statistically significant ?

In [9]:
# Show that you understand common pitfalls.
# lying with statistics: show what is happening within buckets (granularity), or the average of buckets (which misses people moving between them), other pitfalls

## Copying the relevant data

### (obsolete) Selecting topics that include questions relevant for our analysis

In [10]:
Survey_sections = ["Some basic information about who you are",
                   "Employment",
                   "Education + Work + Career",
                   "Tech and culture",
                   "Stack overflow community",
                   "Demographics",
				   "Professional Developer Series",
                   "Teams Questions",
                   "Final thoughts",
				   ]

### Selecting only the responses that are relevant for our analysis

In [11]:
# creating a list of relevant answers

cols_dfa1 = [
					'ResponseID',

                    'MainBranch',
                    'DevType',
                    'ICorPM', #whether technical role or more about leadership, soft skills

					'Age',
                    'Gender',
                    'Accessibility',
                    'Country',

                    'Employment',

					'OrgSize',

                    'CodingActivities',
                    'EdLevel',
                    'LearnCode',
                    'LearnCodeOnline',
                    'LearnCodeCoursesCert',

                    'YearsCode', #asked together
                    'YearsCodePro', #asked together
                    'WorkExp', #under the team section

					'Currency',
                    'CompTotal',
                    'CompFreq',
                    'ConvertedCompYearly',


]


#copying the relevant data into a new data frame
dfa1 = df[cols_dfa1].copy()

#previewing it
dfa1.head()

,ResponseID,MainBranch,DevType,ICorPM,Age,Gender,Accessibility,Country,Employment,OrgSize,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,WorkExp,Currency,CompTotal,CompFreq,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,NaN,NaN,NaN,NaN,NaN,Canada,"Employed, full-time",NaN,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAD\tCanadian dollar,NaN,NaN,NaN
2,3,"I am not primarily a developer, but I write co...",Data scientist or machine learning specialist;...,NaN,25-34 years old,Man,None of the above,United Kingdom of Great Britain and Northern I...,"Employed, full-time",20 to 99 employees,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,NaN,GBP\tPound sterling,32000.0,Yearly,40205.0
3,4,I am a developer by profession,"Developer, full-stack",NaN,35-44 years old,Man,None of the above,Israel,"Employed, full-time",100 to 499 employees,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,NaN,ILS\tIsraeli new shekel,60000.0,Monthly,215232.0
4,5,I am a developer by profession,"Developer, front-end;Developer, full-stack;Dev...",NaN,25-34 years old,NaN,NaN,United States of America,"Employed, full-time",20 to 99 employees,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,NaN,USD\tUnited States dollar,NaN,NaN,NaN

## Data Understanding

See which columns need processing for simplifying

In [12]:
#adjust the column width such that the whole content is seen
pd.set_option('display.max_colwidth', 120)

#visualize the schema: qname (abreviation) - question (long form)
dfs[dfs["type"] == 'MC'][["qid","qname", "question"]].sort_values(by='qid')

#print(dfs[["qname", "question"]])

,qid,qname,question
3,2,MainBranch,"Which of the following options best describes you today? Here, by ""developer"" we mean ""someone who writes code."" <b>..."
18,6,Country,"Where do you live? <span style=""font-weight: bolder;"">*</span>"
8,25,EdLevel,Which of the following best describes the highest level of formal education that you’ve completed? *
15,29,OrgSize,Approximately how many people are employed by the company or organization you currently work for?
14,31,DevType,Which of the following describes your current job? Please select all that apply.
12,32,YearsCode,"Including any education, how many years have you been coding in total?"
13,34,YearsCodePro,"NOT including education, how many years have you coded professionally (as a part of your work)?"
19,50,Currency,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable est..."
21,52,CompFreq,"Is that compensation weekly, monthly, or yearly?"
39,100,SOVisitFreq,How frequently would you say you visit Stack Overflow?
40,101,SOAccount,Do you have a Stack Overflow account?
41,102,SOPartFreq,"How frequently would you say you participate in Q&amp;A on Stack Overflow? By participate we mean ask, answer, vote ..."
42,106,SOComm,Do you consider yourself a member of the Stack Overflow community?
45,122,Gender,"Which of the following describe you, if any? Please check all that apply."
49,124,Accessibility,"Which of the following describe you, if any? Please check all that apply."
50,125,MentalHealth,"Which of the following describe you, if any? Please check all that apply."
48,126,Ethnicity,"Which of the following describe you, if any? Please check all that apply."
44,127,Age,What is your age?
64,132,SurveyLength,How do you feel about the length of the survey this year?
65,133,SurveyEase,How easy or difficult was this survey to complete?
47,136,Sexuality,"Which of the following describe you, if any? Please check all that apply."
46,153,Trans,Do you identify as transgender?
38,266,NEWSOSites,Which of the following Stack Overflow sites have you visited? Select all that apply.
9,276,LearnCode,How did you learn to code? Select all that apply.
16,278,PurchaseInfluence,"What level of influence do you, personally, have over new technology purchases at your organization?"
17,279,BuyNewTool,"When buying a new tool or software, how do you discover and research available solutions? Select all that apply."
10,281,LearnCodeOnline,What online resources do you use to learn to code? Select all that apply.
31,283,VersionControlSystem,What are the primary <b>version control systems</b> you use? Select all that apply.
32,284,VCInteraction,How do you interact with your version control system? Select all that apply.
61,286,SOTeamsUsage,Does your team use Stack Overflow for Teams?
53,287,ICorPM,Are you an independent contributor or people manager?
67,289,Knowledge_2,"Knowledge silos prevent me from getting ideas across the organization (i.e., one individual or team has information ..."
72,289,Knowledge_7,Waiting on answers to questions often causes interruptions and disrupts my workflow.
71,289,Knowledge_6,I often find myself answering questions that I’ve already answered before.
66,289,Knowledge_1,I have interactions with people outside of my immediate team.
70,289,Knowledge_5,I know which system or resource to use to find information and answers to questions I have.
68,289,Knowledge_3,I can find up-to-date information within my organization to help me do my job.
69,289,Knowledge_4,I am able to quickly find answers to my questions with existing tools and resources.
75,290,Frequency_3,Encountering knowledge silos (where one individual or team has information that's not shared or distributed with oth...
74,290,Frequency_2,Interacting with people outside of your immediate team?
73,290,Frequency_1,Needing help from people outside of your immediate team?
57,291,TimeSearching,"On an average day, how much time do you typically spend searching for answers or solutions to problems you encounter..."
58,292,TimeAnswering,"On an average day, how much time do you typically spend answering questions you get asked at work?"
59,293,Onboarding,The time it takes to onboard new hires at my company is:
76,294,TrueFalse_1,Are you involved in supporting new hires during their onboarding?
78,294,TrueFalse_3,Does your employer give you time to learn new skills?
77,294,TrueFalse_2,Do you use learning resources provided by your employer?
4,296,Employment,Which of the following best describes your current employment status?
6,297,CodingActivities,Which of the following best describes the code you write outside of work? Select all that apply.
52,299,TBranch,"<span style=""font-size:16px;"">Would you like to participate in the Professional Developer Series?</span>"
60,304,ProfessionalTech,My company has:
36,305,Blockchain,"How favorable are you about blockchain, crypto, and decentralization?"
11,306,LearnCodeCoursesCert,What online courses or certifications do you use to learn to code? Select all that apply.
5,308,RemoteWork,Which best describes your current work situation?

## Handling missing Data

In [13]:
# compute NaN and:
# make decision of how to handle it and show 2 key approaches and argument

In [14]:
# how many NaN in some important columns

NaN_share = dfa1.isna().mean().round(4) * 100
NaN_share["ConvertedCompYearly"]

48.04

### Convert type to facilitate analysis

In [15]:
# convert numeric values into correct data type
dfa1["YearsCodePro"] = pd.to_numeric(dfa1["YearsCodePro"], errors='coerce').astype('Int64')
dfa1[["YearsCodePro"]]

       YearsCodePro
0              <NA>
1              <NA>
2                 5
3                17
4                 3
...             ...
73263             5
73264             5
73265            33
73266            31
73267             5

[73268 rows x 1 columns]

## Exploding nested responses

In [16]:
#View the nested columns possible unique values

#define the columns that need dummies
nested_cols = ['DevType', 'Employment', 'CodingActivities', 'LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert']
ID_col = ['ResponseID']

sel = ID_col + nested_cols

dfa1_nested_cols = dfa1[sel].copy()

dfa1_nested_cols

nested_cols_unique_values = {}

for col in nested_cols:
	dfa1_nested_cols[col] = dfa1_nested_cols[col].str.split(';')
	#print(col)
	exploded_col = dfa1_nested_cols.explode(col).reset_index(drop=True)
	unique_values_col = exploded_col[col].unique().tolist()

	#clear of NaN because that will be embedded in the new table otherwise
	if np.nan in unique_values_col: unique_values_col.remove(np.nan)

	nested_cols_unique_values[col] = unique_values_col

#dfa1_nested_cols
nested_cols_unique_values

{'DevType': ['Data scientist or machine learning specialist',
  'Developer, front-end',
  'Engineer, data',
  'Engineer, site reliability',
  'Developer, full-stack',
  'Developer, back-end',
  'Developer, desktop or enterprise applications',
  'Developer, QA or test',
  'Student',
  'Developer, mobile',
  'Educator',
  'Engineering manager',
  'Database administrator',
  'Academic researcher',
  'DevOps specialist',
  'Other (please specify):',
  'Developer, embedded applications or devices',
  'Developer, game or graphics',
  'Project manager',
  'Cloud infrastructure engineer',
  'Data or business analyst',
  'Designer',
  'Scientist',
  'Product manager',
  'Senior Executive (C-Suite, VP, etc.)',
  'System administrator',
  'Blockchain',
  'Marketing or sales professional',
  'Security professional'],
 'Employment': ['Employed, full-time',
  'Student, full-time',
  'Student, part-time',
  'Not employed, but looking for work',
  'Independent contractor, freelancer, or self-employed',
  'Employed, part-time',
  'Not employed, and not looking for work',
  'Retired',
  'I prefer not to say'],
 'CodingActivities': ['Hobby',
  'Contribute to open-source projects',
  'I don’t code outside of work',
  'Bootstrapping a business',
  'Freelance/contract work',
  'Other (please specify):',
  'School or academic work'],
 'LearnCode': ['Books / Physical media',
  'Friend or family member',
  'Other online resources (e.g., videos, blogs, forum)',
  'School (i.e., University, College, etc)',
  'On the job training',
  'Online Courses or Certification',
  'Coding Bootcamp',
  'Colleague',
  'Other (please specify):',
  'Hackathons (virtual or in-person)'],
 'LearnCodeOnline': ['Technical documentation',
  'Blogs',
  'Programming Games',
  'Written Tutorials',
  'Stack Overflow',
  'Online books',
  'Video-based Online Courses',
  'Online challenges (e.g., daily or weekly coding challenges)',
  'Online forum',
  'How-to videos',
  'Written-based Online Courses',
  'Auditory material (e.g., podcasts)',
  'Interactive tutorial',
  'Coding sessions (live or recorded)',
  'Other (Please specify):',
  'Certification videos'],
 'LearnCodeCoursesCert': ['Coursera',
  'Udemy',
  'Codecademy',
  'Pluralsight',
  'edX',
  'Udacity',
  'Other',
  'Skillsoft']}

In [17]:
dfa1.head()

,ResponseID,MainBranch,DevType,ICorPM,Age,Gender,Accessibility,Country,Employment,OrgSize,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,WorkExp,Currency,CompTotal,CompFreq,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,NaN,NaN,NaN,NaN,NaN,Canada,"Employed, full-time",NaN,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,CAD\tCanadian dollar,NaN,NaN,NaN
2,3,"I am not primarily a developer, but I write code sometimes as part of my work","Data scientist or machine learning specialist;Developer, front-end;Engineer, data;Engineer, site reliability",NaN,25-34 years old,Man,None of the above,United Kingdom of Great Britain and Northern Ireland,"Employed, full-time",20 to 99 employees,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;Friend or family member;Other online resources (e.g., videos, blogs, forum);School (i.e., Uni...",Technical documentation;Blogs;Programming Games;Written Tutorials;Stack Overflow,NaN,14,5,NaN,GBP\tPound sterling,32000.0,Yearly,40205.0
3,4,I am a developer by profession,"Developer, full-stack",NaN,35-44 years old,Man,None of the above,Israel,"Employed, full-time",100 to 499 employees,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., University, College, etc)",NaN,NaN,20,17,NaN,ILS\tIsraeli new shekel,60000.0,Monthly,215232.0
4,5,I am a developer by profession,"Developer, front-end;Developer, full-stack;Developer, back-end;Developer, desktop or enterprise applications;Develop...",NaN,25-34 years old,NaN,NaN,United States of America,"Employed, full-time",20 to 99 employees,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc);On the job training","Technical documentation;Blogs;Stack Overflow;Online books;Video-based Online Courses;Online challenges (e.g., daily ...",NaN,8,3,NaN,USD\tUnited States dollar,NaN,NaN,NaN

In [18]:

def survey_col_get_dummies(nested_col):

	#should have a test here that lists coincide with expected format


	#create a working copy of ID and relevant column
	dfa1_dummies = dfa1[["ResponseID", nested_col]].copy()

	# replace existing comma with dash to avoid confusion when making lists next
	dfa1_dummies[nested_col] = dfa1_dummies[nested_col].str.replace(", ", " - ")

	# use the semicolon to parse data into lists
	dfa1_dummies[nested_col] = dfa1_dummies[nested_col].str.split(';')

	# do the dummies split and group the individual responses by ResponseID (Participant, responder unique ID)
	dfa1_dummies = pd.get_dummies(dfa1_dummies.explode(nested_col)).groupby('ResponseID').sum()

	return dfa1_dummies



#view a preview of the end result
dfa1_dummies_t = survey_col_get_dummies("DevType")
dfa1_dummies_t

,DevType_Academic researcher,DevType_Blockchain,DevType_Cloud infrastructure engineer,DevType_Data or business analyst,DevType_Data scientist or machine learning specialist,DevType_Database administrator,DevType_Designer,DevType_DevOps specialist,DevType_Developer - QA or test,DevType_Developer - back-end,DevType_Developer - desktop or enterprise applications,DevType_Developer - embedded applications or devices,DevType_Developer - front-end,DevType_Developer - full-stack,DevType_Developer - game or graphics,DevType_Developer - mobile,DevType_Educator,DevType_Engineer - data,DevType_Engineer - site reliability,DevType_Engineering manager,DevType_Marketing or sales professional,DevType_Other (please specify):,DevType_Product manager,DevType_Project manager,DevType_Scientist,DevType_Security professional,DevType_Senior Executive (C-Suite - VP - etc.),DevType_Student,DevType_System administrator
ResponseID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73264,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
73265,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
73266,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73267,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
73268,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,0,0,0,1,0,1,0,0,1,1

In [19]:
# We will be splitting the Nested columns of interest into dummies

#start a new dataframe which will be concatenated with the results
dfa1_dummies_0 = dfa1[["ResponseID"]].copy()

#do the same for each column except "ResponseID"
for col in dfa1.columns.drop("ResponseID"):

	# if the column is MP (that is nested and needs dummies) - then get them and append
	if col in nested_cols:
		dummies_to_add = survey_col_get_dummies(col)
		#replace floats by integers
		# /*/*/*/ To be done
		dfa1_dummies_0 = dfa1_dummies_0.join(dummies_to_add)

	else:
	# if the column does not need dummies, just join with it. double brackets because we want a df not a series
		dfa1_dummies_0 = dfa1_dummies_0.join(dfa1[[col]])

dfa1d = dfa1_dummies_0
dfa1d

,ResponseID,MainBranch,DevType_Academic researcher,DevType_Blockchain,DevType_Cloud infrastructure engineer,DevType_Data or business analyst,DevType_Data scientist or machine learning specialist,DevType_Database administrator,DevType_Designer,DevType_DevOps specialist,DevType_Developer - QA or test,DevType_Developer - back-end,DevType_Developer - desktop or enterprise applications,DevType_Developer - embedded applications or devices,DevType_Developer - front-end,DevType_Developer - full-stack,DevType_Developer - game or graphics,DevType_Developer - mobile,DevType_Educator,DevType_Engineer - data,DevType_Engineer - site reliability,DevType_Engineering manager,DevType_Marketing or sales professional,DevType_Other (please specify):,DevType_Product manager,DevType_Project manager,DevType_Scientist,DevType_Security professional,DevType_Senior Executive (C-Suite - VP - etc.),DevType_Student,DevType_System administrator,ICorPM,Age,Gender,Accessibility,Country,Employment_Employed - full-time,Employment_Employed - part-time,Employment_I prefer not to say,Employment_Independent contractor - freelancer - or self-employed,Employment_Not employed - and not looking for work,Employment_Not employed - but looking for work,Employment_Retired,Employment_Student - full-time,Employment_Student - part-time,OrgSize,CodingActivities_Bootstrapping a business,CodingActivities_Contribute to open-source projects,CodingActivities_Freelance/contract work,CodingActivities_Hobby,CodingActivities_I don’t code outside of work,CodingActivities_Other (please specify):,CodingActivities_School or academic work,EdLevel,LearnCode_Books / Physical media,LearnCode_Coding Bootcamp,LearnCode_Colleague,LearnCode_Friend or family member,LearnCode_Hackathons (virtual or in-person),LearnCode_On the job training,LearnCode_Online Courses or Certification,LearnCode_Other (please specify):,LearnCode_Other online resources (e.g. - videos - blogs - forum),LearnCode_School (i.e. - University - College - etc),LearnCodeOnline_Auditory material (e.g. - podcasts),LearnCodeOnline_Blogs,LearnCodeOnline_Certification videos,LearnCodeOnline_Coding sessions (live or recorded),LearnCodeOnline_How-to videos,LearnCodeOnline_Interactive tutorial,LearnCodeOnline_Online books,LearnCodeOnline_Online challenges (e.g. - daily or weekly coding challenges),LearnCodeOnline_Online forum,LearnCodeOnline_Other (Please specify):,LearnCodeOnline_Programming Games,LearnCodeOnline_Stack Overflow,LearnCodeOnline_Technical documentation,LearnCodeOnline_Video-based Online Courses,LearnCodeOnline_Written Tutorials,LearnCodeOnline_Written-based Online Courses,LearnCodeCoursesCert_Codecademy,LearnCodeCoursesCert_Coursera,LearnCodeCoursesCert_Other,LearnCodeCoursesCert_Pluralsight,LearnCodeCoursesCert_Skillsoft,LearnCodeCoursesCert_Udacity,LearnCodeCoursesCert_Udemy,LearnCodeCoursesCert_edX,YearsCode,YearsCodePro,WorkExp,Currency,CompTotal,CompFreq,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Canada,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,<NA>,NaN,CAD\tCanadian dollar,NaN,NaN,NaN
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,25-34 years old,Man,None of the above,United Kingdom of Great Britain and Northern Ireland,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 to 99 employees,0.0,1.0,0.0,1.0,0.0,0.0,0.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14,5,NaN,GBP\tPound sterling,32000.0,Yearly,40205.0
3,4,I am a developer by profession,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,35-44 years old,Man,None of the above,Israel,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100 to 499 employees,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20,17,NaN,ILS\tIsraeli new shekel,60000.0,Monthly,215232.0
4,5,I am a developer by profession,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,25-34 years old,NaN,NaN,United States of America,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 to 99 employees,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8,3,NaN,USD\tUnited States dollar,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73263,73264,I am a developer by profession,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Independent contributor,25-34 years old,Man,None of the above,Nigeria,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,100 to 499 employees,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8,5,5.0,USD\tUnited States dollar,60000.0,Yearly,NaN
73264,73265,I am a developer by profession,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Independent contributor,25-34 years old,Man,None of the above,United States of America,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,I don’t know,0.0,0.0,1.0,0.0,0.0,0.0,0.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,6,5,6.0,USD\tUnited States dollar,107000.0,Yearly,NaN
73265,73266,"I am not primarily a developer, but I write code sometimes as part of my work",0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Independent contributor,55-64 years old,Man,None of the above,United States of America,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 to 99 employees,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,42,33,42.0,USD\tUnited States dollar,NaN,NaN,NaN
73266,73267,I am a developer by profession,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,55-64 years old,Man,None of the above,United Kingdom of Great Britain and Northern Ireland,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10 to 19 employees,0.0,0.0,0.0,1.0,0.0,0.0,1.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,50,31,NaN,GBP\tPound sterling,58500.0,Yearly,NaN
73267,73268,"I used to be a developer by profession, but no longer am",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,25-34 years old,Man,None of the above,Canada,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16,5,NaN,NaN,NaN,NaN,NaN

In [20]:
cols_dfa1

['ResponseID',
 'MainBranch',
 'DevType',
 'ICorPM',
 'Age',
 'Gender',
 'Accessibility',
 'Country',
 'Employment',
 'OrgSize',
 'CodingActivities',
 'EdLevel',
 'LearnCode',
 'LearnCodeOnline',
 'LearnCodeCoursesCert',
 'YearsCode',
 'YearsCodePro',
 'WorkExp',
 'Currency',
 'CompTotal',
 'CompFreq',
 'ConvertedCompYearly']

In [21]:
# which questions are we focusing on
mask = dfs["qname"].isin(cols_dfa1)
dfs[mask][["qname", "question"]]

#correct the order to reflect our data frame analysis 1 (dfa1)
order = cols_dfa1.copy()

#remove the columns that are not in the schema
order.remove("ResponseID")
order.remove("ConvertedCompYearly")

#show us the schema in the relevant order
dfa1_schema = dfs.set_index('qname').loc[order].reset_index()
dfa1_schema[["qname", "question"]]

,qname,question
0,MainBranch,"Which of the following options best describes you today? Here, by ""developer"" we mean ""someone who writes code."" <b>..."
1,DevType,Which of the following describes your current job? Please select all that apply.
2,ICorPM,Are you an independent contributor or people manager?
3,Age,What is your age?
4,Gender,"Which of the following describe you, if any? Please check all that apply."
5,Accessibility,"Which of the following describe you, if any? Please check all that apply."
6,Country,"Where do you live? <span style=""font-weight: bolder;"">*</span>"
7,Employment,Which of the following best describes your current employment status?
8,OrgSize,Approximately how many people are employed by the company or organization you currently work for?
9,CodingActivities,Which of the following best describes the code you write outside of work? Select all that apply.
10,EdLevel,Which of the following best describes the highest level of formal education that you’ve completed? *
11,LearnCode,How did you learn to code? Select all that apply.
12,LearnCodeOnline,What online resources do you use to learn to code? Select all that apply.
13,LearnCodeCoursesCert,What online courses or certifications do you use to learn to code? Select all that apply.
14,YearsCode,"Including any education, how many years have you been coding in total?"
15,YearsCodePro,"NOT including education, how many years have you coded professionally (as a part of your work)?"
16,WorkExp,How many years of working experience do you have?
17,Currency,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable est..."
18,CompTotal,"What is your current total compensation (salary, bonuses, and perks, before taxes and deductions)? Please enter a wh..."
19,CompFreq,"Is that compensation weekly, monthly, or yearly?"


## Check if the "Other" kind of response offers some Qualitative Data
### Todo: mantain value of 'Other' categorical data
### Check where it was lost for a given exploded column

In [22]:
dfa1d[dfa1d["LearnCode_Other (please specify):"]==1][["LearnCode_Other (please specify):"]]

       LearnCode_Other (please specify):
22                                   1.0
24                                   1.0
30                                   1.0
47                                   1.0
60                                   1.0
...                                  ...
73197                                1.0
73199                                1.0
73220                                1.0
73230                                1.0
73242                                1.0

[3558 rows x 1 columns]

## Querying a qname to see what it means

In [23]:
dfs[dfs["qname"] == 'ProfessionalTech']

    qid             qname         question force_resp type selector
60  304  ProfessionalTech  My company has:      False   MC     MAVR

## Export data for Tableau before any more changes to the df

In [24]:

# Export the DataFrame to a CSV file
dfa1d.to_csv('../processed-data/dataframe-select-columns-and-exploded.csv', index=False)